name: graph_dot
description: Library for creating Graphviz graphs in the dot language.
version: 1.0.3
repository: https://github.com/yuraMovsesyan/graph_dot

environment:
  sdk: ^3.1.5

dependencies:
  
dev_dependencies:
  lints: ^2.0.0
  # test: ^1.21.0
